[package]
name = "taskboard"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
axum = { version = "0.6.9", optional = true }
leptos = { version = "0.2.4", default-features = false, features = ["stable"] }
tokio = { version = "1.25.0", features = ["rt-multi-thread", "macros"], optional = true }
uuid = { version = "1.3.0", features = ["v4", "js"] }

[features]
default = []
csr = ["leptos/csr"]
hydrate = ["leptos/hydrate"]
ssr = ["leptos/ssr","dep:axum","dep:tokio"]