[package]
name = "taskboard"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
leptos = { version = "0.2.4", features = ["stable"] }
uuid = { version = "1.3.0", features = ["v4", "js"] }
