[package]
name = "taskboard"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
axum = { version = "0.6.9", optional = true }
http = { version = "0.2.9", optional = true }
leptos = { version = "0.2.4", default-features = false, features = ["stable"] }
leptos_axum = { version = "0.2.4", optional = true }
once_cell = { version = "1.17.1", optional = true }
serde = "1.0.152"
serde_json = "1.0.93"
tokio = { version = "1.25.0", features = ["rt-multi-thread", "macros"], optional = true }
tower-http = { version = "0.4.0", features = ["fs"], optional = true }
uuid = { version = "1.3.0", features = ["v4", "js", "serde"] }
wasm-bindgen = "0.2.84"

[features]
default = []
csr = ["leptos/csr"]
hydrate = ["leptos/hydrate"]
ssr = ["leptos/ssr", "dep:axum", "dep:tokio", "dep:http", "dep:tower-http", "dep:once_cell", "dep:leptos_axum"]