name = "taskboard-worker"
compatibility_date = "2023-03-22"
main = "build/worker/shim.mjs"

[build]
command = "cargo install -q worker-build && worker-build --release -- --features=worker"
watch_dir = "src"

[site]
bucket = "pkg"

[[d1_databases]]
binding = "DB"
database_name = "taskboard"
